In [ ]:
#task 1 (numpy)
#import lib
import numpy as np
import pandas as pd
#read data from csv
df = pd.read_csv("dirty_cafe_sales.csv")
#convert it into numeric
df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')
#convert it into numpy array
arr = df["Quantity"].to_numpy()
#remove not a number valaues 
arr = arr[~np.isnan(arr)]
meanvalue=np.mean(arr)
print("Array:", arr)
print("Mean    :", meanvalue)
print("Sum     :", np.sum(arr))
print("Maximum :", np.max(arr))
print("Minimum :", np.min(arr))
print("values greater than the mean value")
print("=================================")
abovemeanvalue=arr[arr>meanvalue]
print("values greater than the mean value: ",abovemeanvalue)

Array: [2. 4. 4. ... 4. 3. 3.]
Mean    : 3.028463396702027
Sum     : 28834.0
Maximum : 5.0
Minimum : 1.0
values greater than the mean value
values greater than the mean value:  [4. 4. 5. ... 4. 4. 4.]


In [21]:
#reshaping an array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshapedarray=arr.reshape(3,4)
print(reshapedarray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
#array 1
arr1=np.array([1,2,3,4,5])
#array 2
arr2=np.array([6,7,8,9,10])
#v stack
vertialstack=np.vstack(arr1)
print(vertialstack)
#h stack 
horizontalstack=np.hstack(arr2)
print(horizontalstack)

[[1]
 [2]
 [3]
 [4]
 [5]]
[ 6  7  8  9 10]


In [31]:
#Pandas
import pandas as pd
data=pd.read_csv("dirty_cafe_sales.csv")
df=pd.DataFrame(data)
print("shape :",df.shape)
print("====================")
print("D type: ",df.dtypes)
print("====================")
print("Null values: ",df.isnull().sum())

shape : (10000, 8)
D type:  Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object
Null values:  Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64


In [32]:
#describe method
import pandas as pd
df = pd.read_csv("dirty_cafe_sales.csv")
print(df["Quantity"].describe())

count     9862
unique       7
top          5
freq      2013
Name: Quantity, dtype: object


In [ ]:
#Filtering
import pandas as pd

df = pd.read_csv("dirty_cafe_sales.csv")

df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce')

average = df["Total Spent"].mean()

above_avg = df[df["Total Spent"] > average]

print("Overall Average:", round(average, 2))
print("Total Rows Above Average:", len(above_avg))
print()
print(above_avg)


Overall Average: 8.92
Total Rows Above Average: 4125

     Transaction ID      Item Quantity Price Per Unit  Total Spent  \
1       TXN_4977031      Cake        4            3.0         12.0   
3       TXN_7034554     Salad        2            5.0         10.0   
5       TXN_2602893  Smoothie        5            4.0         20.0   
6       TXN_4433211   UNKNOWN        3            3.0          9.0   
7       TXN_6699534  Sandwich        4            4.0         16.0   
...             ...       ...      ...            ...          ...   
9990    TXN_1538510    Coffee        5            2.0         10.0   
9991    TXN_3897619  Sandwich        3            4.0         12.0   
9992    TXN_2739140  Smoothie        4            4.0         16.0   
9994    TXN_7851634   UNKNOWN        4            4.0         16.0   
9999    TXN_6170729  Sandwich        3            4.0         12.0   

      Payment Method  Location Transaction Date  
1               Cash  In-store       2023-05-16  
3    

In [ ]:
#multiple conditions at the same time 
import pandas as pd

df = pd.read_csv("dirty_cafe_sales.csv")

df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce')
df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')

filtered = df[(df["Total Spent"] > 10) & (df["Quantity"] >= 3)]

print("Filtered Rows:", len(filtered))
print()
print(filtered)

Filtered Rows: 2978

     Transaction ID      Item  Quantity Price Per Unit  Total Spent  \
1       TXN_4977031      Cake       4.0            3.0         12.0   
5       TXN_2602893  Smoothie       5.0            4.0         20.0   
7       TXN_6699534  Sandwich       4.0            4.0         16.0   
8       TXN_4717867       NaN       5.0            3.0         15.0   
9       TXN_2064365  Sandwich       5.0            4.0         20.0   
...             ...       ...       ...            ...          ...   
9989    TXN_1741685     Juice       5.0            3.0         15.0   
9991    TXN_3897619  Sandwich       3.0            4.0         12.0   
9992    TXN_2739140  Smoothie       4.0            4.0         16.0   
9994    TXN_7851634   UNKNOWN       4.0            4.0         16.0   
9999    TXN_6170729  Sandwich       3.0            4.0         12.0   

     Payment Method  Location Transaction Date  
1              Cash  In-store       2023-05-16  
5       Credit Card       Na

In [47]:
#updating value using loc
import pandas as pd

df = pd.read_csv("dirty_cafe_sales.csv")
df=pd.DataFrame(data)
df.loc[1,"Item"]="browni"
# print(df)
#now using iloc
df.iloc[1:2]=5
df.iloc[1,1]="salad"
print("updation using iloc ")
print(df)

updation using iloc 
     Transaction ID      Item Quantity Price Per Unit Total Spent  \
0       TXN_1961373    Coffee        2            2.0         4.0   
1                 5     salad        5              5           5   
2       TXN_4271903    Cookie        4            1.0       ERROR   
3       TXN_7034554     Salad        2            5.0        10.0   
4       TXN_3160411    Coffee        2            2.0         4.0   
...             ...       ...      ...            ...         ...   
9995    TXN_7672686    Coffee        2            2.0         4.0   
9996    TXN_9659401       NaN        3            NaN         3.0   
9997    TXN_5255387    Coffee        4            2.0         8.0   
9998    TXN_7695629    Cookie        3            NaN         3.0   
9999    TXN_6170729  Sandwich        3            4.0        12.0   

      Payment Method  Location Transaction Date  
0        Credit Card  Takeaway       2023-09-08  
1                  5         5                5  


In [50]:
#missing values handle 
import pandas as pd

df = pd.read_csv("dirty_cafe_sales.csv")
print(df.isnull().sum())
# ERROR aur UNKNOWN ko NaN banao pehle
df.replace("ERROR", np.nan, inplace=True)
df.replace("UNKNOWN", np.nan, inplace=True)

# --------------------------------------------------------
# 1. Transaction ID
# Missing ho to drop karo — ye unique identifier hai
# Bina ID ke row ka koi matlab nahi
# --------------------------------------------------------
df.dropna(subset=["Transaction ID"], inplace=True)

# --------------------------------------------------------
# 2. Item
# Mode se fill karo — jo item sabse zyada bika
# Categorical column hai, mean/median nahi chalega
# --------------------------------------------------------
df["Item"].fillna(df["Item"].mode()[0], inplace=True)

# --------------------------------------------------------
# 3. Quantity
# Median se fill karo — numerical hai
# Median isliye kyunki outliers se affect nahi hota
# --------------------------------------------------------
df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')
df["Quantity"].fillna(df["Quantity"].median(), inplace=True)

# --------------------------------------------------------
# 4. Price Per Unit
# Median se fill karo — pricing mein outliers ho sakte hain
# Mean se galat average aa sakta hai
# --------------------------------------------------------
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors='coerce')
df["Price Per Unit"].fillna(df["Price Per Unit"].median(), inplace=True)

# --------------------------------------------------------
# 5. Total Spent
# Mean se fill karo — normally distributed spending
# Zyada outliers nahi hain is column mein
# --------------------------------------------------------
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce')
df["Total Spent"].fillna(df["Total Spent"].mean(), inplace=True)

# --------------------------------------------------------
# 6. Payment Method
# Placeholder "Unknown" se fill karo
# Hum guess nahi kar sakte kaunsa method tha
# --------------------------------------------------------
df["Payment Method"].fillna("Unknown", inplace=True)

# --------------------------------------------------------
# 7. Location
# Placeholder "Unknown" se fill karo
# Categorical hai aur accurately guess nahi ho sakta
# --------------------------------------------------------
df["Location"].fillna("Unknown", inplace=True)

# --------------------------------------------------------
# 8. Transaction Date
# Drop karo — date ke bina transaction incomplete hai
# Time series analysis mein kaam nahi aayega
# --------------------------------------------------------
df.dropna(subset=["Transaction Date"], inplace=True)

# Final check
print("Missing values after cleaning:")
print(df.isnull().sum())
print()
print("Remaining rows:", len(df))

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64
Missing values after cleaning:
Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

Remaining rows: 9540


C:\Users\Zee\AppData\Local\Temp\ipykernel_29252\1304264223.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Item"].fillna(df["Item"].mode()[0], inplace=True)
C:\Users\Zee\AppData\Local\Temp\ipykernel_29252\1304264223.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For 

In [52]:
import pandas as pd
import numpy as np

df = pd.read_csv("dirty_cafe_sales.csv")
df.replace("ERROR", np.nan, inplace=True)
df.replace("UNKNOWN", np.nan, inplace=True)
missing_per_row = df.isnull().sum(axis=1)
print("Missing values per row distribution:")
print(missing_per_row.value_counts())
print("=== Null Check ===")
print(df.isnull().sum())
print()
print("=== Nothing null ===")
print(df.isnull().any().any())
print()
print("=== Total Nulls ===")
print("Total null values:", df.isnull().sum().sum())

Missing values per row distribution:
1    4285
0    3089
2    2136
3     439
4      47
5       4
Name: count, dtype: int64
=== Null Check ===
Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

=== Nothing null ===
True

=== Total Nulls ===
Total null values: 10082


In [53]:
import pandas as pd
import numpy as np

df = pd.read_csv("dirty_cafe_sales.csv")

# Strip whitespace + fix casing
text_columns = ["Item", "Payment Method", "Location"]

for col in text_columns:
    df[col] = df[col].str.strip()
    df[col] = df[col].str.title()

print(df[["Item", "Payment Method", "Location"]].head(10))

       Item  Payment Method  Location
0    Coffee     Credit Card  Takeaway
1      Cake            Cash  In-Store
2    Cookie     Credit Card  In-Store
3     Salad         Unknown   Unknown
4    Coffee  Digital Wallet  In-Store
5  Smoothie     Credit Card       NaN
6   Unknown           Error  Takeaway
7  Sandwich            Cash   Unknown
8       NaN             NaN  Takeaway
9  Sandwich             NaN  In-Store


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("dirty_cafe_sales.csv")
informal_nulls = ["N/A", "none", "-", "None", "n/a", 
                  "ERROR", "UNKNOWN", "unknown", "", " "]

df.replace(informal_nulls, np.nan, inplace=True)

print("Nulls after replacement:")
print(df.isnull().sum())

Nulls after replacement:
Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64


In [55]:
import pandas as pd
import numpy as np

df = pd.read_csv("dirty_cafe_sales.csv")
df.replace(["ERROR", "UNKNOWN"], np.nan, inplace=True)
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce')
df["Total Spent"].fillna(df["Total Spent"].median(), inplace=True)

median_val = df["Total Spent"].median()

df["Transaction Label"] = df["Total Spent"].apply(
    lambda x: "High" if x > median_val else "Low"
)

print("Median:", median_val)
print(df[["Total Spent", "Transaction Label"]].head(10))

Median: 8.0
   Total Spent Transaction Label
0          4.0               Low
1         12.0              High
2          8.0               Low
3         10.0              High
4          4.0               Low
5         20.0              High
6          9.0              High
7         16.0              High
8         15.0              High
9         20.0              High


C:\Users\Zee\AppData\Local\Temp\ipykernel_29252\1311464644.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total Spent"].fillna(df["Total Spent"].median(), inplace=True)


In [56]:
import pandas as pd

df = pd.read_csv("dirty_cafe_sales.csv")

print("Before:", len(df))

df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

print("After :", len(df))
print(df.head())

Before: 10000
After : 10000
  Transaction ID    Item Quantity Price Per Unit Total Spent  Payment Method  \
0    TXN_1961373  Coffee        2            2.0         4.0     Credit Card   
1    TXN_4977031    Cake        4            3.0        12.0            Cash   
2    TXN_4271903  Cookie        4            1.0       ERROR     Credit Card   
3    TXN_7034554   Salad        2            5.0        10.0         UNKNOWN   
4    TXN_3160411  Coffee        2            2.0         4.0  Digital Wallet   

   Location Transaction Date  
0  Takeaway       2023-09-08  
1  In-store       2023-05-16  
2  In-store       2023-07-19  
3   UNKNOWN       2023-04-27  
4  In-store       2023-06-11  


In [57]:
import pandas as pd
import numpy as np

df = pd.read_csv("dirty_cafe_sales.csv")
df.replace(["ERROR", "UNKNOWN"], np.nan, inplace=True)
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce')

grouped = df.groupby("Item")["Total Spent"].agg(
    Total_Sales='sum',
    Average_Transaction='mean'
).round(2)

print(grouped)

          Total_Sales  Average_Transaction
Item                                      
Cake           9933.0                 9.13
Coffee         6784.0                 6.08
Cookie         3070.0                 2.97
Juice          9984.0                 8.95
Salad         16605.0                15.15
Sandwich      12956.0                12.17
Smoothie      12556.0                12.26
Tea            4735.5                 4.55


In [58]:
import pandas as pd
import numpy as np

df = pd.read_csv("dirty_cafe_sales.csv")
df.replace(["ERROR", "UNKNOWN"], np.nan, inplace=True)

most_used = df["Payment Method"].value_counts()

print("Payment Method Usage:")
print(most_used)
print()
print("Most Used:", most_used.idxmax())

Payment Method Usage:
Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

Most Used: Digital Wallet


C:\Users\Zee\AppData\Local\Temp\ipykernel_29252\792865430.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Item"].fillna(df["Item"].mode()[0], inplace=True)
C:\Users\Zee\AppData\Local\Temp\ipykernel_29252\792865430.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For ex

✅ File saved as cleaned_cafe_sales.csv
Total rows: 9540
